// Generated by Wrangler on Sat May 25 2024 23:46:52 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database;
}
