#:schema node_modules/wrangler/config-schema.json
name = "web2"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB" 
database_name = "Learning"
database_id = "b65d7050-a8b2-45ad-8dac-0a41b4fbc339"
